services:
  catalog:
    build:
      context: .
    hostname: catalog
    # Removed depends_on catalog-db since we are pointing to AWS RDS MySQL
    restart: always
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    environment:
      - GIN_MODE=release
      - reschedule=on-node-failure
      - RETAIL_CATALOG_PERSISTENCE_PROVIDER=mysql
      # Clean configurations matching your active Kubernetes secrets & configuration keys
      - RETAIL_CATALOG_PERSISTENCE_USER=${DB_USERNAME}
      - RETAIL_CATALOG_PERSISTENCE_PASSWORD=${DB_PASSWORD}
      - RETAIL_CATALOG_PERSISTENCE_DB_NAME=catalog
      - RETAIL_CATALOG_PERSISTENCE_ENDPOINT=://amazonaws.com
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    develop:
      watch:
        - action: rebuild
          path: .
