image:
  tag: "1.2.1"

serviceAccount:
  create: false
  name: cart-service-account

app:
  persistence:
    provider: dynamodb
    dynamodb:
      tableName: retailstore-cart
      createTable: false

dynamodb:
  create: false